import type { EmojiIconKey, ItemShape, ItemTier } from "../types/game";

type TierSeed = [name: string, symbol: string, tagline: string];

const tierSeeds: TierSeed[] = [
  ["Tiny Smile", "🙂", "A small face with room to grow."],
  ["Bright Smile", "😀", "The first upgrade feels bigger immediately."],
  ["Happy Smile", "😃", "More expression, better payouts."],
  ["Mega Grin", "😄", "A wide grin with a stronger coin pulse."],
  ["Spark Face", "🤩", "A starry icon that starts to look premium."],
  ["Party Face", "🥳", "The board begins to celebrate every match."],
  ["Cool Face", "😎", "A confident mascot with faster earnings."],
  ["Crown Face", "👑", "The smile graduates into a tiny crown."],
  ["Bronze Badge", "🥉", "A compact badge with visible rank."],
  ["Silver Badge", "🥈", "A cleaner badge with sharper rewards."],
  ["Gold Badge", "🥇", "A bright milestone for early players."],
  ["Gem Badge", "💎", "A glossy icon with better revenue density."],
  ["Mini Cart", "🛒", "Small demand starts moving across the board."],
  ["Pop-Up Shop", "🏪", "A real storefront replaces the starter face."],
  ["Coin Counter", "🪙", "Money becomes the icon itself."],
  ["Gift Kiosk", "🎁", "A compact upgrade with reward energy."],
  ["Tool Desk", "🧰", "Useful gear starts scaling the operation."],
  ["Design Desk", "🎨", "Color and polish raise the tier identity."],
  ["Music Booth", "🎧", "A brighter booth that pays on rhythm."],
  ["Arcade Pod", "🕹️", "A playful pod with stronger idle value."],
  ["Delivery Van", "🚚", "The first icon that feels mobile."],
  ["Launch Bike", "🛵", "A faster delivery loop for bigger boards."],
  ["Smart Cafe", "☕", "A small social hub with steady income."],
  ["Glow Lab", "🧪", "Experiments turn into coin-positive loops."],
  ["Creator Hub", "🎬", "Content becomes a durable upgrade."],
  ["Signal Hub", "📡", "The board starts broadcasting value."],
  ["Data Core", "💾", "Storage and signals stack into worth."],
  ["Circuit Lab", "🔌", "Power flows through every merge."],
  ["Robot Desk", "🤖", "Automation joins the merge chain."],
  ["Sky Pad", "🛸", "The icons now feel beyond street level."],
  ["Rocket Cart", "🚀", "Launch energy pushes the next band."],
  ["Solar Roof", "☀️", "A bright asset with cleaner revenue."],
  ["Cloud Office", "☁️", "The operation floats above the city."],
  ["Finance Vault", "🏦", "A heavier icon with serious payouts."],
  ["Media Tower", "📺", "Attention turns into an asset class."],
  ["Cyber Shield", "🛡️", "Protection becomes profitable."],
  ["Talent Stage", "🎤", "Bigger teams make the icon louder."],
  ["Factory Bay", "🏭", "Production now fills the tile."],
  ["Commerce Grid", "🧭", "The board connects demand in every direction."],
  ["Capital Tower", "🏢", "A tall icon that reads as a real upgrade."],
  ["AI Concierge", "🧠", "Smart service scales the whole board."],
  ["Quantum Gate", "🔷", "A sharp gate into late-game value."],
  ["Logistics Ring", "🔗", "Every route feeds the next one."],
  ["Green Foundry", "♻️", "Efficient loops raise the coin floor."],
  ["Studio Campus", "🏛️", "One icon now implies a whole campus."],
  ["Venture Bank", "💰", "Capital gets dense and easy to read."],
  ["Signal Exchange", "📈", "Market shifts become playable progress."],
  ["Nano Factory", "⚙️", "Small parts create massive output."],
  ["Cloud District", "🌐", "The empire spreads across networks."],
  ["Orbit Market", "🛰️", "Commerce reaches above the skyline."],
  ["Fusion Lab", "⚛️", "Energy unlocks a new reward band."],
  ["Holo Retail", "🔮", "The icon starts to feel rare."],
  ["Deeptech Campus", "🧬", "Research stacks into a visual trophy."],
  ["Moonshot Studio", "🌙", "A late-game target with clear scale."],
  ["Empire Exchange", "🏙️", "The city itself becomes the tile."],
  ["Neon Megastore", "🌆", "A landmark upgrade with heavy glow."],
  ["Orbital Holdings", "🪐", "Portfolio gravity bends the board."],
  ["Singularity Bank", "✨", "A tiny sparkle carrying huge value."],
  ["Infinity Market", "♾️", "Demand loops without a ceiling."],
  ["Crown Empire", "👑", "The final icon owns the whole run."],
];

const palettes = [
  "from-cyan-300 to-blue-500",
  "from-fuchsia-300 to-pink-500",
  "from-emerald-300 to-teal-500",
  "from-amber-200 to-orange-500",
  "from-violet-300 to-indigo-500",
  "from-rose-200 to-red-500",
];

const emojiIconAssets: Record<EmojiIconKey, string> = {
  smile: new URL("../../assets/iconscout-emoji/smile.png", import.meta.url).href,
  happyFace: new URL("../../assets/iconscout-emoji/happy-face.png", import.meta.url).href,
  cryingLaugh: new URL("../../assets/iconscout-emoji/crying-laugh.png", import.meta.url).href,
  winkFace: new URL("../../assets/iconscout-emoji/wink-face.png", import.meta.url).href,
  tongueWink: new URL("../../assets/iconscout-emoji/tongue-wink.png", import.meta.url).href,
  starryEyes: new URL("../../assets/iconscout-emoji/starry-eyes.png", import.meta.url).href,
  smileyGlasses: new URL("../../assets/iconscout-emoji/smiley-glasses.png", import.meta.url).href,
  loveEyes: new URL("../../assets/iconscout-emoji/love-eyes.png", import.meta.url).href,
  loveMoney: new URL("../../assets/iconscout-emoji/love-money.png", import.meta.url).href,
  partyFace: new URL("../../assets/iconscout-emoji/party-face.png", import.meta.url).href,
  mindBlown: new URL("../../assets/iconscout-emoji/mind-blown.png", import.meta.url).href,
  shockedFace: new URL("../../assets/iconscout-emoji/shocked-face.png", import.meta.url).href,
  confusedFace: new URL("../../assets/iconscout-emoji/confused-face.png", import.meta.url).href,
  disappointedFace: new URL("../../assets/iconscout-emoji/disappointed-face.png", import.meta.url).href,
  monocleFace: new URL("../../assets/iconscout-emoji/monocle-face.png", import.meta.url).href,
  raisedEyebrow: new URL("../../assets/iconscout-emoji/raised-eyebrow.png", import.meta.url).href,
  goofyFace: new URL("../../assets/iconscout-emoji/goofy-face.png", import.meta.url).href,
  sadPensive: new URL("../../assets/iconscout-emoji/sad-pensive.png", import.meta.url).href,
  sunglassesFace: new URL("../../assets/iconscout-emoji/sunglasses-face.png", import.meta.url).href,
  smirkingFace: new URL("../../assets/iconscout-emoji/smirking-face.png", import.meta.url).href,
  fireEyes: new URL("../../assets/iconscout-emoji/fire-eyes.png", import.meta.url).href,
  angryFace: new URL("../../assets/iconscout-emoji/angry-face.png", import.meta.url).href,
  coldFace: new URL("../../assets/iconscout-emoji/cold-face.png", import.meta.url).href,
  coolPixelFace: new URL("../../assets/iconscout-emoji/cool-pixel-face.png", import.meta.url).href,
  crazyLove: new URL("../../assets/iconscout-emoji/crazy-love.png", import.meta.url).href,
  cryingFace: new URL("../../assets/iconscout-emoji/crying-face.png", import.meta.url).href,
  devilFace: new URL("../../assets/iconscout-emoji/devil-face.png", import.meta.url).href,
  laughingFace: new URL("../../assets/iconscout-emoji/laughing-face.png", import.meta.url).href,
  moneyEye: new URL("../../assets/iconscout-emoji/money-eye.png", import.meta.url).href,
  cuteApple: new URL("../../assets/iconscout-emoji/cute-apple.png", import.meta.url).href,
  confuseOrange: new URL("../../assets/iconscout-emoji/confuse-orange.png", import.meta.url).href,
  cuteWatermelon: new URL("../../assets/iconscout-emoji/cute-watermelon.png", import.meta.url).href,
  happyAvocado: new URL("../../assets/iconscout-emoji/happy-avocado.png", import.meta.url).href,
  happyCarrot: new URL("../../assets/iconscout-emoji/happy-carrot.png", import.meta.url).href,
  sadTomato: new URL("../../assets/iconscout-emoji/sad-tomato.png", import.meta.url).href,
  twinBabyCarrot: new URL("../../assets/iconscout-emoji/twin-baby-carrot.png", import.meta.url).href,
  basketball: new URL("../../assets/iconscout-emoji/basketball.png", import.meta.url).href,
  archery: new URL("../../assets/iconscout-emoji/archery.png", import.meta.url).href,
  football: new URL("../../assets/iconscout-emoji/football.png", import.meta.url).href,
  goldMedal: new URL("../../assets/iconscout-emoji/gold-medal.png", import.meta.url).href,
  gymnastic: new URL("../../assets/iconscout-emoji/gymnastic.png", import.meta.url).href,
};

const iconProgression: Array<{ iconKey: EmojiIconKey; shape: ItemShape }> = [
  { iconKey: "smile", shape: "circle" },
  { iconKey: "happyFace", shape: "bubble" },
  { iconKey: "laughingFace", shape: "flower" },
  { iconKey: "cryingLaugh", shape: "circle" },
  { iconKey: "winkFace", shape: "drop" },
  { iconKey: "tongueWink", shape: "pill" },
  { iconKey: "starryEyes", shape: "ticket" },
  { iconKey: "loveEyes", shape: "circle" },
  { iconKey: "crazyLove", shape: "flower" },
  { iconKey: "smileyGlasses", shape: "gem" },
  { iconKey: "sunglassesFace", shape: "bubble" },
  { iconKey: "coolPixelFace", shape: "pill" },
  { iconKey: "moneyEye", shape: "ticket" },
  { iconKey: "loveMoney", shape: "bubble" },
  { iconKey: "partyFace", shape: "flower" },
  { iconKey: "goofyFace", shape: "drop" },
  { iconKey: "confusedFace", shape: "pill" },
  { iconKey: "raisedEyebrow", shape: "gem" },
  { iconKey: "monocleFace", shape: "circle" },
  { iconKey: "smirkingFace", shape: "bubble" },
  { iconKey: "disappointedFace", shape: "drop" },
  { iconKey: "sadPensive", shape: "pill" },
  { iconKey: "cryingFace", shape: "flower" },
  { iconKey: "mindBlown", shape: "gem" },
  { iconKey: "shockedFace", shape: "drop" },
  { iconKey: "coldFace", shape: "circle" },
  { iconKey: "angryFace", shape: "bubble" },
  { iconKey: "devilFace", shape: "gem" },
  { iconKey: "fireEyes", shape: "flower" },
  { iconKey: "cuteApple", shape: "circle" },
  { iconKey: "confuseOrange", shape: "bubble" },
  { iconKey: "cuteWatermelon", shape: "drop" },
  { iconKey: "happyAvocado", shape: "pill" },
  { iconKey: "happyCarrot", shape: "ticket" },
  { iconKey: "sadTomato", shape: "flower" },
  { iconKey: "twinBabyCarrot", shape: "gem" },
  { iconKey: "basketball", shape: "circle" },
  { iconKey: "football", shape: "bubble" },
  { iconKey: "archery", shape: "drop" },
  { iconKey: "gymnastic", shape: "pill" },
  { iconKey: "goldMedal", shape: "ticket" },
];

export const ITEM_TIERS: ItemTier[] = tierSeeds.map(([name, symbol, tagline], index) => {
  const iconStep = iconProgression[index % iconProgression.length];

  return {
    tier: index + 1,
    name,
    symbol,
    iconKey: iconStep.iconKey,
    icon: emojiIconAssets[iconStep.iconKey],
    shape: iconStep.shape,
    tagline,
    palette: palettes[index % palettes.length],
    revenue: Math.round(10 * Math.pow(index + 1, 1.9) + index * 10),
    xp: Math.round(5 * Math.pow(index + 1, 1.32)),
  };
});

export const MAX_TIER = ITEM_TIERS.length;

export function getTier(tier: number): ItemTier {
  return ITEM_TIERS[Math.max(0, Math.min(ITEM_TIERS.length - 1, tier - 1))];
}

export function getUnlockedTiers(highestTier: number): ItemTier[] {
  return ITEM_TIERS.slice(0, Math.max(1, Math.min(highestTier, ITEM_TIERS.length)));
}
